### ISSUE TITLE
cannot connect ui to public-pool api

### ISSUE THREAD

**Issue by warioishere** [benjamin-wilson/public-pool-ui#17]
the title states the problem.
Everything runs on the same system. Public-pool runs fine and is already connected with my bitaxe

But ui doesnt seem to get a connection to the public-pool

my .env of public pool:

```
# bitcoin node running in your private network 192.168.1.0/24
#BITCOIN_RPC_URL=http://172.16.1.58

# bitcoin node running undockered on the same PC
# needs to add rpcallowip=172.16.0.0/12 to your bitcoin.conf
BITCOIN_RPC_URL=http://host.docker.internal

BITCOIN_RPC_USER=xxx
BITCOIN_RPC_PASSWORD=xxx
BITCOIN_RPC_PORT=8332
BITCOIN_RPC_TIMEOUT=10000

# You can use this instead of BITCOIN_RPC_USER and BITCOIN_RPC_PASSWORD
#BITCOIN_RPC_COOKIEFILE=

# Enable in bitcoin.conf with
# zmqpubrawblock=tcp://*:3000
BITCOIN_ZMQ_HOST="tcp://172.16.1.58:3000"

API_PORT=3334
STRATUM_PORT=3333

#optional telegram bot
#TELEGRAM_BOT_TOKEN=

#optional discord bot
#DISCORD_BOT_CLIENTID=
#DISCORD_BOT_GUILD_ID=
#DISCORD_BOT_CHANNEL_ID=

#optional
DEV_FEE_ADDRESS=
# mainnet | testnet
NETWORK=mainnet

API_SECURE=false
```

my enviroment.prod.ts:

```
export const environment = {
    production: true,
    API_URL: 'http://host.docker.internal:32793',
    STRATUM_URL: 'blitzpool.yourdevice.ch:32792'
};
```

my docker-compose-yml of the public pool:

```
version: '3.8'

services:
  public-pool:
    container_name: public-pool
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "32792:3333"
      - "32793:3334"
    volumes:
      - "./${NETWORK}-DB:/public-pool/DB"
      - "./.env:/public-pool/.env:ro"
    environment:
      - NODE_ENV=production
```

the docker command I am using to setup public-pool-ui:

`docker run --name public-pool-ui -d -p 8081:80 -e DOMAIN=public-pool.yourdevice.ch public-pool-ui`

any idea? the docker logs of the public-ui continer doesnt show any useful informations
