### ISSUE TITLE
Difficulty to install the Web-UI on my NAS (Portainer)

### ISSUE THREAD

**Issue by TheKogoro** [benjamin-wilson/public-pool-ui#25]
Hello, 

I have installed my Bitcoin node and the Public-pool, it working, i was able to connect my NerdAxe and i see it make many Shares, so i think it's working.

I have tried to install the WEBUI with Portainer as i have do (With also many dificulties) with the public-pool. but i was unable to make it work proprelly. I can acces to the webpage, it load sucefully but i get no data on it (nothing on Uptime and Online device (if i put my bitcoin adress i see nothing). 

I doesnt great at coding or with linux/docker (i'ts already great i was able working the node and the pool ^^.

I require somes help for set up the Webui (with portainer if it is possible) or other easy way to do. 

The bitcoin node, the Mining Pool and WebUi is on the same Portainer Network

Here is my Stack i use on portainer:

```
services:
  bitcoin:
    image: ruimarinho/bitcoin-core:latest
    container_name: bitcoin-node
    ports:
      - "8332:8332" # RPC port
      - "8333:8333" # P2P port
    environment:
      - BITCOIN_NETWORK=mainnet
      - BITCOIN_RPC_USER=*****
      - BITCOIN_RPC_PASSWORD=*****
      - BITCOIN_RPC_ALLOWIP=172.24.0.0/16
      - BITCOIN_ZMQPUBRAWBLOCK=tcp://*:3000
      - BITCOIN_ZMQPUBRAWTX=tcp://*:3001
    volumes:
      - /volume1/Docker/bitcoin-data:/home/bitcoin/.bitcoin
    networks:
      - mining-network
    restart: always

  mining-pool:
    image: sethforprivacy/public-pool:latest
    container_name: mining-pool
    ports:
      - "3333:3333" # Stratum port
      - "3334:3334" # API port
    environment:
      - BITCOIN_RPC_URL=http://bitcoin-node
      - BITCOIN_RPC_PORT=8332
      - BITCOIN_RPC_USER=*****
      - BITCOIN_RPC_PASSWORD=*****
      - BITCOIN_RPC_TIMEOUT=10000
      - BITCOIN_ZMQ_HOST=tcp://bitcoin-node:3000
      - API_PORT=3334
      - STRATUM_PORT=3333
      - NETWORK=mainnet
      - DOMAIN=pool.baka-news-network.ch
    depends_on:
      - bitcoin
    volumes:
      - /volume1/Docker/public-pool:/app/data


    networks:
      - mining-network
    restart: always

  web-ui:
    image: ghcr.io/sethforprivacy/public-pool-ui:latest
    container_name: mining-pool-webui
    ports:
      - 8080:80  # Accédez au Web UI via http://votre-ip:8080
      - 8443:443 #Https
    volumes:
      - ./${NETWORK}-DB:/public-pool/DB
      - ./.env:/public-pool/.env:ro
    environment:
      - NODE_ENV=production
      - API_URL=http://pool.baka-news-network.ch:3334   # Remplacer par l'adresse de votre API du pool
      - STRATUM_URL=pool.baka-news-network.ch:3333   # L'adresse de votre serveur de minage
      - STRATUM_PORT=3333   # Port du Stratum
      - API_PORT=3334   # Port de l'API
      - NETWORK=mainnet  # Ou testnet, selon ce que vous utilisez
    networks:
      - mining-network
    restart: always


networks:
  mining-network:
    driver: bridge
```

Thats what i get from firefox when i inspect the page, i dont know how the website work but i can access at miner info if i put on firefox: http://pool.baka-news-network.ch:3334/api/info and other api page i can manually see info. So if i understand proprely, normally the website need to get this info on thoses adress but it use the wrong one.

```
Uncaught SyntaxError: import declarations may only appear at top level of a module [scripts.21e2572554dc843d.js:1:1](http://192.168.1.21:8080/scripts.21e2572554dc843d.js)
XHRGET
http://192.168.1.21:8080/api/info/chart
[HTTP/1.1 404 Not Found 3ms]

XHRGET
http://192.168.1.21:8080/api/info
[HTTP/1.1 404 Not Found 4ms]

XHRGET
http://192.168.1.21:8080/api/network
[HTTP/1.1 404 Not Found 2ms]

ERROR 
Object { headers: {…}, status: 404, statusText: "Not Found", url: "http://192.168.1.21:8080/api/info", ok: false, name: "HttpErrorResponse", message: "Http failure response for http://192.168.1.21:8080/api/info: 404 Not Found", error: null }
[main.e8333acb87f9e56e.js:1:41288](http://192.168.1.21:8080/main.e8333acb87f9e56e.js)
ERROR 
Object { headers: {…}, status: 404, statusText: "Not Found", url: "http://192.168.1.21:8080/api/info", ok: false, name: "HttpErrorResponse", message: "Http failure response for http://192.168.1.21:8080/api/info: 404 Not Found", error: null }
[main.e8333acb87f9e56e.js:1:41288](http://192.168.1.21:8080/main.e8333acb87f9e56e.js)
ERROR 
Object { headers: {…}, status: 404, statusText: "Not Found", url: "http://192.168.1.21:8080/api/info", ok: false, name: "HttpErrorResponse", message: "Http failure response for http://192.168.1.21:8080/api/info: 404 Not Found", error: null }
[main.e8333acb87f9e56e.js:1:41288](http://192.168.1.21:8080/main.e8333acb87f9e56e.js)
ERROR 
Object { headers: {…}, status: 404, statusText: "Not Found", url: "http://192.168.1.21:8080/api/info", ok: false, name: "HttpErrorResponse", message: "Http failure response for http://192.168.1.21:8080/api/info: 404 Not Found", error: null }
[main.e8333acb87f9e56e.js:1:41288](http://192.168.1.21:8080/main.e8333acb87f9e56e.js)
ERROR 
Object { headers: {…}, status: 404, statusText: "Not Found", url: "http://192.168.1.21:8080/api/info/chart", ok: false, name: "HttpErrorResponse", message: "Http failure response for http://192.168.1.21:8080/api/info/chart: 404 Not Found", error: null }
[main.e8333acb87f9e56e.js:1:41288](http://192.168.1.21:8080/main.e8333acb87f9e56e.js)

```
​

Thanks in advance for your help.
